// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqDx8xp0qYTnFaZXr6FDO4AbM_8MbNX1A',
    appId: '1:322531788955:web:ebad17d62af89ebc0ede3e',
    messagingSenderId: '322531788955',
    projectId: 'smart-parking-app-tih',
    authDomain: 'smart-parking-app-tih.firebaseapp.com',
    storageBucket: 'smart-parking-app-tih.appspot.com',
    measurementId: 'G-QSJY3VMHFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4jf_WMlUObgs7jIObJ7wA-2oHU0KMTvE',
    appId: '1:322531788955:android:1c7cccd3228a67fe0ede3e',
    messagingSenderId: '322531788955',
    projectId: 'smart-parking-app-tih',
    storageBucket: 'smart-parking-app-tih.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3vB54BYfVtTa_kNiGipDCSFxxZCnWP3o',
    appId: '1:322531788955:ios:5f7e623b0bc6c88a0ede3e',
    messagingSenderId: '322531788955',
    projectId: 'smart-parking-app-tih',
    storageBucket: 'smart-parking-app-tih.appspot.com',
    iosClientId: '322531788955-kobkueai77f23b4q3jn64e5gn0e940f0.apps.googleusercontent.com',
    iosBundleId: 'com.example.seatLayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3vB54BYfVtTa_kNiGipDCSFxxZCnWP3o',
    appId: '1:322531788955:ios:5f7e623b0bc6c88a0ede3e',
    messagingSenderId: '322531788955',
    projectId: 'smart-parking-app-tih',
    storageBucket: 'smart-parking-app-tih.appspot.com',
    iosClientId: '322531788955-kobkueai77f23b4q3jn64e5gn0e940f0.apps.googleusercontent.com',
    iosBundleId: 'com.example.seatLayout',
  );
}
